#!/bin/bash

source /app/.env

set -xe

export RAILS_ENV=${RAILS_ENV:=production}

onexit() {
  echo SIGINT received
  echo sending SIGTERM to all processes
  children=$(ps --ppid=$$ -o pid='')
  kill -- $children &> /dev/null
  sleep 8s
}
trap onexit SIGTERM SIGINT EXIT

/usr/sbin/sshd
/usr/bin/redis-server /etc/redis/redis.conf

cd /home/git/gitlab
su git -c "bundle exec rake assets:precompile RAILS_ENV=$RAILS_ENV"
su git -c "bundle exec unicorn_rails -c config/unicorn.rb -E $RAILS_ENV -p 8080" &
su git -c "bundle exec sidekiq -q post_receive,mailer,system_hook,project_web_hook,gitlab_shell,common,default -e $RAILS_ENV -P tmp/pids/sidekiq.pd" >> log/sidekiq.log 2>&1 &

wait
